CREATE TABLE einsaetze
(
    einsatznummer                       VARCHAR(200),
    datum                               VARCHAR(200),
    meldender                           VARCHAR(200),
    telefonnummerdesmeldenden           VARCHAR(200),
    meldeweg                            VARCHAR(200),
    einsatzstichwort                    VARCHAR(200),
    meldebild                           VARCHAR(200),
    ort                                 VARCHAR(200),
    ortsteil                            VARCHAR(200),
    strasse                             VARCHAR(200),
    hausnummer                          VARCHAR(200),
    objekt                              VARCHAR(200),
    unterobjekt                         VARCHAR(200),
    ortszusatz                          VARCHAR(200),
    bemerkungeinsatzort                 VARCHAR(200),
    bemerkungeinsatzanlass              VARCHAR(200),
    rueckrufnummer                      VARCHAR(200),
    rueckrufbemerkung                   VARCHAR(200),
    gefahrenmeldeanlage                 VARCHAR(200),
    einsatzplaninfo                     VARCHAR(200),
    infotext                            VARCHAR(200),
    plz                                 VARCHAR(200),
    strassenabschnitt                   VARCHAR(200),
    einsatzortkoordinatenordwgs84       VARCHAR(200),
    einsatzortkoordinateostwgs84        VARCHAR(200),
    fremdalternativekoordinatenordwgs84 VARCHAR(200),
    fremdalternativekoordinateostwgs84  VARCHAR(200),
    transportartrlp                     VARCHAR(200),
    einsatzmittel                       VARCHAR(1000),
    meldungen                           VARCHAR(1000),
    massnahmen                          VARCHAR(1000)
);

